---
title: "Microglia response to glutamate uncaging"
author: "alexandria hughes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(ggpubr)
library(cowplot)
library(colorspace)
```

```{r}
theme_set(theme_cowplot(font_size =18))
```

```{r}
glu_unc <- read_csv('tidy-glu-uncaging-microglia.csv')
#head(glu_unc)
```

calc net directed movements
```{r}
glu_unc <- glu_unc %>% mutate(net_gain2 = unc_new+opp_lost-opp_new-unc_lost, new = unc_new - opp_new, total_movement=unc_new+opp_new+unc_lost+opp_lost, start_processes =unc_start+opp_start)
```

```{r}
#View(glu_unc)
```


```{r}
ggplot(glu_unc, aes(x=group, y=net_gain2, fill=group))+
   geom_violin(aes(x=group, y=net_gain2), fill = "#E3C22D", color= "#777777", size=1, alpha=0.5, linetype="longdash", scale="width", trim=FALSE, draw_quantiles = c(0.25, 0.5, 0.75))+
  geom_jitter(width=0.2, height=0.05, shape=21, size=7, alpha=0.75)+
  scale_fill_manual(values = c("#FFC5FF", "#FFC5FF"))+
  stat_compare_means(method="wilcox.test", label = "p.format", size=5.5, label.x=1.375)+
  theme(legend.position="none")+
  labs(x=" ", y="Net directed movements / cell")
#ggsave('glu-unc-net-gain4.png', dpi=300, width=6, height=4.5)
        
```

```{r}
ggplot(glu_unc, aes(x=group, y=total_movement, fill=group))+
   geom_violin(aes(x=group, y=total_movement), fill = "#E3C22D", color= "#777777", size=1, alpha=0.5, linetype="longdash", scale="width", trim=FALSE, draw_quantiles = c(0.25, 0.5, 0.75))+
  geom_jitter(width=0.2, height=0.05, shape=21, size=7, alpha=0.75)+
  scale_fill_manual(values = c("#FFC5FF", "#FFC5FF"))+
  stat_compare_means(method="wilcox.test", label = "p.format", size=5.5, label.x=1.375)+
  theme(legend.position="none")+
  labs(x=" ", y="Process movements / cell")
#ggsave('glu-unc-all-movements.png', dpi=300, width=6, height=4.5)
```

