---
title: "Fig 1: eight hour timelapse"
author: "alexandria hughes"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```


```{r message=FALSE}
library(tidyverse)
library(ggpubr)
library(cowplot)
library(colorspace)
```

```{r}
theme_set(theme_cowplot(font_size =18))
```

time in minutes, # of microglia passing through territory counted in acqs
```{r}
eighthrs <- read_csv('eight-hour-microglia-visits.csv')
eighthrs
```

```{r}
eighthrs <- eighthrs %>% mutate(microglia_pereight = (microglia / time)*480, permicroglia = (time/microglia), `Visiting microglia` = c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)) 
```

summary stats: median time between microglia visits; number of microglia visiting (on average) in 8 hours
```{r}
eighthrs %>% summarize(med_time_to_mic = median(permicroglia), med_per_eight = mean(microglia_pereight))
```

PLOT time to microglia arrival
```{r}
ggplot(eighthrs, aes(x=`Visiting microglia`, y=permicroglia))+
  geom_violin(aes(x=`Visiting microglia`, y=permicroglia), fill = "#E3C22D", color= "#777777", size=1, alpha=0.5, linetype="longdash", scale="width", trim=FALSE, draw_quantiles = c(0.25, 0.5, 0.75))+
  geom_jitter(width=0.23, height=0.025, shape=21, size=6, alpha=0.75, fill="#FFC5FF")+
  scale_x_discrete()+
  labs(y="Time / # microglia visits (min)", x="")
#ggsave('time-to-mic-visit.png', dpi=300, width=4.5, height=4.5)
```
